services:
  postgres:
    image: postgres:latest
    container_name: biblotech-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  server:
    profiles:
      - production
    build:
      context: .
    environment:
      DB_HOST: postgres
      DB_NAME: library
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "8080:8080"

volumes:
  postgres-data:
